version: '3.8'
services:
  api:
    build: ./backend
    container_name: snapqr_api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - minio

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: snapqr
      POSTGRES_PASSWORD: snapqr_pass
      POSTGRES_DB: snapqr_db
    ports:
      - "5432:5432"
    volumes: [db_data:/var/lib/postgresql/data]

  minio:
    image: minio/minio
    container_name: snapqr_minio
    command: server /data
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "9000:9000"
    volumes: [minio_data:/data]

  mobile:
    build:
      context: ./mobile
    container_name: snapqr_mobile
    ports:
      - "8081:8081"
    volumes:
      - ./mobile:/app
      - /app/node_modules
    command: yarn start --host 0.0.0.0
    env_file: .env
    depends_on:
      - api

volumes:
  db_data:
  minio_data:

